### ISSUE TITLE
Computer Science

### ISSUE THREAD

**Issue by Bryce1010** [Bryce1010/bryce1010-ACM-Template#7]
## Computer Science

- [Github 中文排行榜](https://github.com/kon9chunkit/GitHub-Chinese-Top-Charts)

  GitHub中文排行榜，帮助你发现高分优秀中文项目、更高效地吸收国人的优秀经验成果；榜单每周更新一次，敬请关注！  

- **Amazing Developers** On YouTube  [[github]](https://github.com/ErikCH/DevYouTubeList)  

### 10.1 Computer Science    

- [ ] CS Books资源  [[ref]](https://github.com/iamshuaidi/CS-Book)
- **Programming Notes for Professionals books** [[url]](https://goalkicker.com/)
- 自学计算机科学 [[github]](https://github.com/keithnull/TeachYourselfCS-CN/blob/master/TeachYourselfCS-CN.md)  
- 程序员修炼之路 [[github]](https://github.com/Snailclimb/programmer-advancement)  
- 互联网上的免费书籍 [[github]](https://github.com/ruanyf/free-books)
- 计算机科学资源列表(Computer Science Resources) [[github]](https://github.com/the-akira/Computer-Science-Resources)   
- 个人**电子书收藏**目录 [[google sheet]](https://docs.google.com/spreadsheets/d/1kwWgRQkOraYsDIHupj_LOhhMAjnnFE2nchQAOycA6z8/edit#gid=0)    
- Waking Up **计算机基础**（计算机网络/操作系统/数据库/Git...）面试问题全面总结 [[github]](https://github.com/wolverinn/Waking-Up)     

#### 数学  

- [MIT 18.01](https://ocw.mit.edu/courses/mathematics/18-01-single-variable-calculus-fall-2006/)，[MIT 18.02](https://ocw.mit.edu/courses/mathematics/18-02-multivariable-calculus-fall-2007/)：微积分  
- [MIT 18.06](https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/)：线性代数
- [Harvard Stat110](https://projects.iq.harvard.edu/stat110/home)：概率论
- [MIT 6.042J](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-spring-2015/)：Mathematics for Computer Science.  

#### CS导论

- [ ] [MIT 6.001](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/)：Introduction to Computer Science and Programming in Python  
- [ ] MIT《计算机科学“补漏”课》(2020)  [[bilibili]](https://www.bilibili.com/read/cv5087259?column_from=5&from=upFeed&native.theme=0&night=0)   

#### 数据结构与算法

[CMU 15-213](https://www.cs.cmu.edu/~213/)：教材是CSAPP。

[MIT 6.824](https://pdos.csail.mit.edu/6.824/)：分布式系统。不久前终于感人地放出视频了。

[MIT 6.828](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-828-operating-system-engineering-fall-2012/)：其实还没看，小伙伴都说好。

[MIT 6.004](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-004-computation-structures-spring-2017/)：Computer Structure。偏硬件，老师讲得很好。

Modern Operating System

[Stanford CS41](https://stanfordpython.com/): Python Language Programming. 可惜没有视频，作业挺有意思的。其实我觉得学语言比较好的一种方式就是学了语法之后做一些练手的项目、作业，这样会掌握得比较快。

[Stanford CS106L](http://web.stanford.edu/class/cs106l/): C++ Language Programming. 前文也介绍过了，我觉得那本Full Course Reader写得真的很好，推荐一下~

#### 机器学习  

[Coursera Andrew NG的Machine Learning](https://www.coursera.org/learn/machine-learning)：机器学习之路从这里开始。

[Stanford CS229](http://cs229.stanford.edu/)：Machine Learning. Youtube上有视频。

[CMU 15-701](http://www.cs.cmu.edu/~mgormley/courses/10701-f16/schedule.html)：Intro to Machine Learning. 就找到这么一年有视频的。

[Coursera PGM](https://www.coursera.org/specializations/probabilistic-graphical-models)：知名课程。

[CMU 15-708](http://www.cs.cmu.edu/~epxing/Class/10708-19/lectures/)：Probabilistic Graphical Model 我只看过两个Lecture。

下面有几本书，不过还是推荐和课程一起看。

Pattern Classification (PC)：比较老的书了，但是内容还是很有意义。

Elements of Statistical Learning：insight很多。

Pattern Recognition and Machine Learning (PRML)

Machine Learning: a Probabilistic Approach (MLAPP)

Information Theory, Inference, and Learning：可惜David J. C. MacKay英年早逝。

#### 深度学习

[Stanford CS231n](http://cs231n.github.io/)：Deep learning for CV. 推荐深度学习从这里开始

[Stanford CS224n](http://web.stanford.edu/class/cs224n/)：Deep learning for NLP.

[Berkeley CS285](http://rll.berkeley.edu/deeprlcourse/)：Deep RL. 我只挑着看了几个Lecture，小伙伴说好。

[Deep Learning Book](https://www.deeplearningbook.org/)：花书。

#### 1. C++  

- Bryce1010-**ACM**-Module + 找工作 [[github]](https://github.com/Bryce1010/bryce1010-ACM-Module/blob/master/README.md)  
- [ ] Cpp进阶
- [ ] cpp reference[[url]](http://www.cplusplus.com/reference/)
- [ ] Algorithmic Flash Cards (算法和数据结构) [[github]](https://github.com/teivah/algodeck)      
- [ ] C++ Primer 课后习题及答案 [[weixin]](https://mp.weixin.qq.com/s/AliA0telmz54msRbMgWc2A)   
- [ ] C++那些事 [[github]](https://github.com/Light-City/CPlusPlusThings)  
- [ ] modern-cpp-features [[github]](https://github.com/AnthonyCalandra/modern-cpp-features)   

#### 2. Front-End

- MDN web Docs [[url]](https://developer.mozilla.org/zh-CN/)   

- [ ] 来自硅谷的JavaScript入门课 [[zhihu]](https://www.zhihu.com/xen/market/specials/1144588903792185344?utm_campaign=zhihumarket&utm_medium=social&utm_source=qq&utm_content=)

- [ ] 前端入门 [[zhihu]](http://t.cn/A6hPnn0t?m=4470379752367132&u=5899938216)  

- 【个人项目】Personal Learning Front-end Project [[github]](https://github.com/Bryce1010/Learning_Front_End)  

- [ ] Front-end Performance (The only Front-End Performance Checklist that runs faster than the others)  [[github]](https://github.com/thedaviddias/Front-End-Performance-Checklist#how-to-use) 

#### 3. Docker  

- [ ] Docker - Beginners / Intermediate / Advanced  [[github]](https://github.com/collabnix/dockerlabs)

#### 4. Golang

- 7天用Go动手写系列[从零实现] [[github]](https://github.com/geektutu/7days-golang)   

#### 1. Linux

- [ ] [Hacker Tools](https://www.youtube.com/watch?v=dbDRfmH5uSI&list=PLyzOVJj3bHQuiujH1lpn8cA9dsyulbYRv&index=3)
- [x] git fort & pull request [[ref]](https://github.com/selfteaching/the-craft-of-selfteaching/issues/67)  

- [ ] An introduction to Git and Github [[book]](

- [ ] The art of Command line  [[github]](https://github.com/jlevy/the-art-of-command-line/blob/master/README-zh.md)   

- [ ] MIT 6.824: Distributed Systems [[youtube]](MIT 6.824: Distributed Systems) [[scheduler]](https://pdos.csail.mit.edu/6.824/schedule.html)  

- [ ] 阮一峰 Bash命令教程 [[blog]](http://www.ruanyifeng.com/blog/2020/04/bash-tutorial.html)

### 4. 算法与数据结构

- [ ] Algorithms by Princeton [[couresa]](https://www.coursera.org/learn/algorithms-part1) [[website]](https://algs4.cs.princeton.edu/home/)

### 5. 体系结构 组成原理  

- [ ] The Hardware/Software Interface from Washington [[course]](https://www.classcentral.com/course/hwswinterface-453)

**Comment by Bryce1010** [comment]
#### 数学  

- [MIT 18.01](https://ocw.mit.edu/courses/mathematics/18-01-single-variable-calculus-fall-2006/)，[MIT 18.02](https://ocw.mit.edu/courses/mathematics/18-02-multivariable-calculus-fall-2007/)：微积分  
- [MIT 18.06](https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/)：线性代数
- [Harvard Stat110](https://projects.iq.harvard.edu/stat110/home)：概率论
- [MIT 6.042J](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-spring-2015/)：Mathematics for Computer Science.  

#### CS导论

- [ ] [MIT 6.001](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/)：Introduction to Computer Science and Programming in Python  
- [ ] MIT《计算机科学“补漏”课》(2020)  [[bilibili]](https://www.bilibili.com/read/cv5087259?column_from=5&from=upFeed&native.theme=0&night=0)   

#### 数据结构与算法

[CMU 15-213](https://www.cs.cmu.edu/~213/)：教材是CSAPP。

[MIT 6.824](https://pdos.csail.mit.edu/6.824/)：分布式系统。不久前终于感人地放出视频了。

[MIT 6.828](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-828-operating-system-engineering-fall-2012/)：其实还没看，小伙伴都说好。

[MIT 6.004](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-004-computation-structures-spring-2017/)：Computer Structure。偏硬件，老师讲得很好。

- [ ] 6.006 Introduction to Algorithms
    - Srini Devadas, Professor at MIT;
    -  一定要做他们的练习题，不然无法保证你真的理解了这些算法

Modern Operating System

[Stanford CS41](https://stanfordpython.com/): Python Language Programming. 可惜没有视频，作业挺有意思的。其实我觉得学语言比较好的一种方式就是学了语法之后做一些练手的项目、作业，这样会掌握得比较快。

[Stanford CS106L](http://web.stanford.edu/class/cs106l/): C++ Language Programming. 前文也介绍过了，我觉得那本Full Course Reader写得真的很好，推荐一下~

- Distributed Computer Systems
    - Srinivasan Keshav, Professor of Computer Science at the University of Cambridge  



#### 机器学习  

[Coursera Andrew NG的Machine Learning](https://www.coursera.org/learn/machine-learning)：机器学习之路从这里开始。

[Stanford CS229](http://cs229.stanford.edu/)：Machine Learning. Youtube上有视频。

[CMU 15-701](http://www.cs.cmu.edu/~mgormley/courses/10701-f16/schedule.html)：Intro to Machine Learning. 就找到这么一年有视频的。

[Coursera PGM](https://www.coursera.org/specializations/probabilistic-graphical-models)：知名课程。

[CMU 15-708](http://www.cs.cmu.edu/~epxing/Class/10708-19/lectures/)：Probabilistic Graphical Model 我只看过两个Lecture。

下面有几本书，不过还是推荐和课程一起看。

Pattern Classification (PC)：比较老的书了，但是内容还是很有意义。

Elements of Statistical Learning：insight很多。

Pattern Recognition and Machine Learning (PRML)

Machine Learning: a Probabilistic Approach (MLAPP)

Information Theory, Inference, and Learning：可惜David J. C. MacKay英年早逝。

#### 深度学习

[Stanford CS231n](http://cs231n.github.io/)：Deep learning for CV. 推荐深度学习从这里开始

[Stanford CS224n](http://web.stanford.edu/class/cs224n/)：Deep learning for NLP.

[Berkeley CS285](http://rll.berkeley.edu/deeprlcourse/)：Deep RL. 我只挑着看了几个Lecture，小伙伴说好。

[Deep Learning Book](https://www.deeplearningbook.org/)：花书。



### 10.2 编程语言  

#### 1. C++  

- Bryce1010-**ACM**-Module + 找工作 [[github]](https://github.com/Bryce1010/bryce1010-ACM-Module/blob/master/README.md)  
- [ ] Cpp进阶
- [ ] cpp reference[[url]](http://www.cplusplus.com/reference/)
- [ ] Algorithmic Flash Cards (算法和数据结构) [[github]](https://github.com/teivah/algodeck)      
- [ ] C++ Primer 课后习题及答案 [[weixin]](https://mp.weixin.qq.com/s/AliA0telmz54msRbMgWc2A)   
- [ ] C++那些事 [[github]](https://github.com/Light-City/CPlusPlusThings)  
- [ ] modern-cpp-features [[github]](https://github.com/AnthonyCalandra/modern-cpp-features)   

#### 2. Front-End

- MDN web Docs [[url]](https://developer.mozilla.org/zh-CN/)   

- [ ] 来自硅谷的JavaScript入门课 [[zhihu]](https://www.zhihu.com/xen/market/specials/1144588903792185344?utm_campaign=zhihumarket&utm_medium=social&utm_source=qq&utm_content=)

- [ ] 前端入门 [[zhihu]](http://t.cn/A6hPnn0t?m=4470379752367132&u=5899938216)  

- 【个人项目】Personal Learning Front-end Project [[github]](https://github.com/Bryce1010/Learning_Front_End)  

- [ ] Front-end Performance (The only Front-End Performance Checklist that runs faster than the others)  [[github]](https://github.com/thedaviddias/Front-End-Performance-Checklist#how-to-use) 

#### 3. Docker  

- [ ] Docker - Beginners / Intermediate / Advanced  [[github]](https://github.com/collabnix/dockerlabs)



#### 4. Golang

- 7天用Go动手写系列[从零实现] [[github]](https://github.com/geektutu/7days-golang)   



### 10.3 操作系统

#### 1. Linux

- [ ] [Hacker Tools](https://www.youtube.com/watch?v=dbDRfmH5uSI&list=PLyzOVJj3bHQuiujH1lpn8cA9dsyulbYRv&index=3)
- [x] git fort & pull request [[ref]](https://github.com/selfteaching/the-craft-of-selfteaching/issues/67)  

- [ ] An introduction to Git and Github [[book]](

- [ ] The art of Command line  [[github]](https://github.com/jlevy/the-art-of-command-line/blob/master/README-zh.md)   

- [ ] MIT 6.824: Distributed Systems [[youtube]](MIT 6.824: Distributed Systems) [[scheduler]](https://pdos.csail.mit.edu/6.824/schedule.html)  

- [ ] 阮一峰 Bash命令教程 [[blog]](http://www.ruanyifeng.com/blog/2020/04/bash-tutorial.html)


### 4. 算法与数据结构

- [ ] Algorithms by Princeton [[couresa]](https://www.coursera.org/learn/algorithms-part1) [[website]](https://algs4.cs.princeton.edu/home/)





### 5. 体系结构 组成原理  

- [ ] The Hardware/Software Interface from Washington [[course]](https://www.classcentral.com/course/hwswinterface-453)  

  



### 6. 计算机网络

**Comment by Bryce1010** [comment]
#### CS导论

- [ ] [MIT 6.001](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/)：Introduction to Computer Science and Programming in Python  
- [ ] MIT《计算机科学“补漏”课》(2020)  [[bilibili]](https://www.bilibili.com/read/cv5087259?column_from=5&from=upFeed&native.theme=0&night=0)

**Comment by Bryce1010** [comment]
#### 数据结构与算法

[CMU 15-213](https://www.cs.cmu.edu/~213/)：教材是CSAPP。

[MIT 6.824](https://pdos.csail.mit.edu/6.824/)：分布式系统。不久前终于感人地放出视频了。

[MIT 6.828](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-828-operating-system-engineering-fall-2012/)：其实还没看，小伙伴都说好。

[MIT 6.004](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-004-computation-structures-spring-2017/)：Computer Structure。偏硬件，老师讲得很好。

- [ ] 6.006 Introduction to Algorithms
    - Srini Devadas, Professor at MIT;
    -  一定要做他们的练习题，不然无法保证你真的理解了这些算法

Modern Operating System

[Stanford CS41](https://stanfordpython.com/): Python Language Programming. 可惜没有视频，作业挺有意思的。其实我觉得学语言比较好的一种方式就是学了语法之后做一些练手的项目、作业，这样会掌握得比较快。

[Stanford CS106L](http://web.stanford.edu/class/cs106l/): C++ Language Programming. 前文也介绍过了，我觉得那本Full Course Reader写得真的很好，推荐一下~

- Distributed Computer Systems
    - Srinivasan Keshav, Professor of Computer Science at the University of Cambridge  



#### 机器学习  

[Coursera Andrew NG的Machine Learning](https://www.coursera.org/learn/machine-learning)：机器学习之路从这里开始。

[Stanford CS229](http://cs229.stanford.edu/)：Machine Learning. Youtube上有视频。

[CMU 15-701](http://www.cs.cmu.edu/~mgormley/courses/10701-f16/schedule.html)：Intro to Machine Learning. 就找到这么一年有视频的。

[Coursera PGM](https://www.coursera.org/specializations/probabilistic-graphical-models)：知名课程。

[CMU 15-708](http://www.cs.cmu.edu/~epxing/Class/10708-19/lectures/)：Probabilistic Graphical Model 我只看过两个Lecture。

下面有几本书，不过还是推荐和课程一起看。

Pattern Classification (PC)：比较老的书了，但是内容还是很有意义。

Elements of Statistical Learning：insight很多。

Pattern Recognition and Machine Learning (PRML)

Machine Learning: a Probabilistic Approach (MLAPP)

Information Theory, Inference, and Learning：可惜David J. C. MacKay英年早逝。

#### 深度学习

[Stanford CS231n](http://cs231n.github.io/)：Deep learning for CV. 推荐深度学习从这里开始

[Stanford CS224n](http://web.stanford.edu/class/cs224n/)：Deep learning for NLP.

[Berkeley CS285](http://rll.berkeley.edu/deeprlcourse/)：Deep RL. 我只挑着看了几个Lecture，小伙伴说好。

[Deep Learning Book](https://www.deeplearningbook.org/)：花书。



### 10.2 编程语言  

#### 1. C++  

- Bryce1010-**ACM**-Module + 找工作 [[github]](https://github.com/Bryce1010/bryce1010-ACM-Module/blob/master/README.md)  
- [ ] Cpp进阶
- [ ] cpp reference[[url]](http://www.cplusplus.com/reference/)
- [ ] Algorithmic Flash Cards (算法和数据结构) [[github]](https://github.com/teivah/algodeck)      
- [ ] C++ Primer 课后习题及答案 [[weixin]](https://mp.weixin.qq.com/s/AliA0telmz54msRbMgWc2A)   
- [ ] C++那些事 [[github]](https://github.com/Light-City/CPlusPlusThings)  
- [ ] modern-cpp-features [[github]](https://github.com/AnthonyCalandra/modern-cpp-features)   

#### 2. Front-End

- MDN web Docs [[url]](https://developer.mozilla.org/zh-CN/)   

- [ ] 来自硅谷的JavaScript入门课 [[zhihu]](https://www.zhihu.com/xen/market/specials/1144588903792185344?utm_campaign=zhihumarket&utm_medium=social&utm_source=qq&utm_content=)

- [ ] 前端入门 [[zhihu]](http://t.cn/A6hPnn0t?m=4470379752367132&u=5899938216)  

- 【个人项目】Personal Learning Front-end Project [[github]](https://github.com/Bryce1010/Learning_Front_End)  

- [ ] Front-end Performance (The only Front-End Performance Checklist that runs faster than the others)  [[github]](https://github.com/thedaviddias/Front-End-Performance-Checklist#how-to-use) 

#### 3. Docker  

- [ ] Docker - Beginners / Intermediate / Advanced  [[github]](https://github.com/collabnix/dockerlabs)



#### 4. Golang

- 7天用Go动手写系列[从零实现] [[github]](https://github.com/geektutu/7days-golang)   



### 10.3 操作系统

#### 1. Linux

- [ ] [Hacker Tools](https://www.youtube.com/watch?v=dbDRfmH5uSI&list=PLyzOVJj3bHQuiujH1lpn8cA9dsyulbYRv&index=3)
- [x] git fort & pull request [[ref]](https://github.com/selfteaching/the-craft-of-selfteaching/issues/67)  

- [ ] An introduction to Git and Github [[book]](

- [ ] The art of Command line  [[github]](https://github.com/jlevy/the-art-of-command-line/blob/master/README-zh.md)   

- [ ] MIT 6.824: Distributed Systems [[youtube]](MIT 6.824: Distributed Systems) [[scheduler]](https://pdos.csail.mit.edu/6.824/schedule.html)  

- [ ] 阮一峰 Bash命令教程 [[blog]](http://www.ruanyifeng.com/blog/2020/04/bash-tutorial.html)


### 4. 算法与数据结构

- [ ] Algorithms by Princeton [[couresa]](https://www.coursera.org/learn/algorithms-part1) [[website]](https://algs4.cs.princeton.edu/home/)





### 5. 体系结构 组成原理  

- [ ] The Hardware/Software Interface from Washington [[course]](https://www.classcentral.com/course/hwswinterface-453)  

  



### 6. 计算机网络

**Comment by Bryce1010** [comment]
#### Modern Operating System

[Stanford CS41](https://stanfordpython.com/): Python Language Programming. 可惜没有视频，作业挺有意思的。其实我觉得学语言比较好的一种方式就是学了语法之后做一些练手的项目、作业，这样会掌握得比较快。

[Stanford CS106L](http://web.stanford.edu/class/cs106l/): C++ Language Programming. 前文也介绍过了，我觉得那本Full Course Reader写得真的很好，推荐一下~

- Distributed Computer Systems
    - Srinivasan Keshav, Professor of Computer Science at the University of Cambridge

**Comment by Bryce1010** [comment]
#### 机器学习  

[Coursera Andrew NG的Machine Learning](https://www.coursera.org/learn/machine-learning)：机器学习之路从这里开始。

[Stanford CS229](http://cs229.stanford.edu/)：Machine Learning. Youtube上有视频。

[CMU 15-701](http://www.cs.cmu.edu/~mgormley/courses/10701-f16/schedule.html)：Intro to Machine Learning. 就找到这么一年有视频的。

[Coursera PGM](https://www.coursera.org/specializations/probabilistic-graphical-models)：知名课程。

[CMU 15-708](http://www.cs.cmu.edu/~epxing/Class/10708-19/lectures/)：Probabilistic Graphical Model 我只看过两个Lecture。

下面有几本书，不过还是推荐和课程一起看。

Pattern Classification (PC)：比较老的书了，但是内容还是很有意义。

Elements of Statistical Learning：insight很多。

Pattern Recognition and Machine Learning (PRML)

Machine Learning: a Probabilistic Approach (MLAPP)

Information Theory, Inference, and Learning：可惜David J. C. MacKay英年早逝。

**Comment by Bryce1010** [comment]
#### 深度学习

[Stanford CS231n](http://cs231n.github.io/)：Deep learning for CV. 推荐深度学习从这里开始

[Stanford CS224n](http://web.stanford.edu/class/cs224n/)：Deep learning for NLP.

[Berkeley CS285](http://rll.berkeley.edu/deeprlcourse/)：Deep RL. 我只挑着看了几个Lecture，小伙伴说好。

[Deep Learning Book](https://www.deeplearningbook.org/)：花书。

**Comment by Bryce1010** [comment]
### 10.2 编程语言  

#### 1. C++  

- Bryce1010-**ACM**-Module + 找工作 [[github]](https://github.com/Bryce1010/bryce1010-ACM-Module/blob/master/README.md)  
- [ ] Cpp进阶
- [ ] cpp reference[[url]](http://www.cplusplus.com/reference/)
- [ ] Algorithmic Flash Cards (算法和数据结构) [[github]](https://github.com/teivah/algodeck)      
- [ ] C++ Primer 课后习题及答案 [[weixin]](https://mp.weixin.qq.com/s/AliA0telmz54msRbMgWc2A)   
- [ ] C++那些事 [[github]](https://github.com/Light-City/CPlusPlusThings)  
- [ ] modern-cpp-features [[github]](https://github.com/AnthonyCalandra/modern-cpp-features)

**Comment by Bryce1010** [comment]
#### 2. Front-End

- MDN web Docs [[url]](https://developer.mozilla.org/zh-CN/)   

- [ ] 来自硅谷的JavaScript入门课 [[zhihu]](https://www.zhihu.com/xen/market/specials/1144588903792185344?utm_campaign=zhihumarket&utm_medium=social&utm_source=qq&utm_content=)

- [ ] 前端入门 [[zhihu]](http://t.cn/A6hPnn0t?m=4470379752367132&u=5899938216)  

- 【个人项目】Personal Learning Front-end Project [[github]](https://github.com/Bryce1010/Learning_Front_End)  

- [ ] Front-end Performance (The only Front-End Performance Checklist that runs faster than the others)  [[github]](https://github.com/thedaviddias/Front-End-Performance-Checklist#how-to-use) 

#### 3. Docker  

- [ ] Docker - Beginners / Intermediate / Advanced  [[github]](https://github.com/collabnix/dockerlabs)



#### 4. Golang

- 7天用Go动手写系列[从零实现] [[github]](https://github.com/geektutu/7days-golang)

**Comment by Bryce1010** [comment]
### 10.3 操作系统

#### 1. Linux

- [ ] [Hacker Tools](https://www.youtube.com/watch?v=dbDRfmH5uSI&list=PLyzOVJj3bHQuiujH1lpn8cA9dsyulbYRv&index=3)
- [x] git fort & pull request [[ref]](https://github.com/selfteaching/the-craft-of-selfteaching/issues/67)  

- [ ] An introduction to Git and Github [[book]](

- [ ] The art of Command line  [[github]](https://github.com/jlevy/the-art-of-command-line/blob/master/README-zh.md)   

- [ ] MIT 6.824: Distributed Systems [[youtube]](MIT 6.824: Distributed Systems) [[scheduler]](https://pdos.csail.mit.edu/6.824/schedule.html)  

- [ ] 阮一峰 Bash命令教程 [[blog]](http://www.ruanyifeng.com/blog/2020/04/bash-tutorial.html)

**Comment by Bryce1010** [comment]
### 4. 算法与数据结构

- [ ] Algorithms by Princeton [[couresa]](https://www.coursera.org/learn/algorithms-part1) [[website]](https://algs4.cs.princeton.edu/home/)





### 5. 体系结构 组成原理  

- [ ] The Hardware/Software Interface from Washington [[course]](https://www.classcentral.com/course/hwswinterface-453)  

  



### 6. 计算机网络

**Comment by Bryce1010** [comment]
### 7. Database  
- [ ] Intro to Database System [[youtube]](https://www.youtube.com/watch?v=y5IShB9ihds&list=PLhMnuBfGeCDPtyC9kUf_hG_QwjYzZ0Am1)
